languageCode = "pt-br"
languageName = "Português"
weight = 2
title = "Portfolio"

[params]
displayName = "PT-BR"
isoCode = "pt-BR"
rtl = false
dateFormat = "2 de January de 2006"

[author]
name = "Luiz Glomyer"
headline = "amogus"
image = "img/pfp.jpg"
bio = "sobre mim"
links = [
  { github = "https://github.com/LuizGlomyer" },
  { linkedin = "https://linkedin.com/in/luiz-glomyer" },
  { email = "glomyerjunior@hotmail.com" },
  { youtube = "https://www.youtube.com/@LuizGlomyer" },
  { whatsapp = "https://wa.me/5592981319982" },
]
