languageCode = "en"
languageName = "English"
weight = 1
title = "Portfolio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "January 2 2006"

[params.author]
name = "Luiz Glomyer"
headline = "Software Developer"
image = "img/pfp.jpg"
bio = "I am passionate about knowledge, I always seek to learn new things and improve myself as a person."
links = [
  { github = "https://github.com/LuizGlomyer" },
  { linkedin = "https://linkedin.com/in/luiz-glomyer" },
  { email = "mailto:glomyerjunior@hotmail.com" },
  { youtube = "https://www.youtube.com/@LuizGlomyer" },
  { whatsapp = "https://wa.me/5592981319982" },
]
