[[main]]
none = "none"

[[main]]
name = "postagens"
pageRef = "posts"
identifier = "LDqSCamIGM"
weight = 1

[[main]]
name = "sobre"
pageRef = "about"
identifier = "3iNIwabkr0"
weight = 2

[[main]]
name = "experiência"
pageRef = "experience"
identifier = "tBh2XUBOsj"
weight = 3

[[main]]
name = "projetos"
pageRef = "projects"
identifier = "PIgSVVIucH"
weight = 4

[[footer]]
none = "none"
