[[main]]
none = "none"

[[main]]
name = "posts"
pageRef = "posts"
identifier = "LDqSCamIGM"
weight = 1

[[main]]
name = "about"
pageRef = "about"
identifier = "3iNIwabkr0"
weight = 2

[[main]]
name = "experience"
pageRef = "experience"
identifier = "tBh2XUBOsj"
weight = 3

[[main]]
name = "projects"
pageRef = "projects"
identifier = "PIgSVVIucH"
weight = 4

[[footer]]
none = "none"
